name: YAML Validation

on: [push, pull_request]

jobs:
  yaml-validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install yamllint
      run: pip install yamllint

    - name: Validate YAML files
      run: yamllint -c .yamllint .
